name: Generate Image List

on:
  push:
    branches:
      - main

jobs:
  images:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v4

    - name: Generate images.json
      run: |
        python << 'EOF'
        import os
        import json

        image_dir = "images"

        exts = (".jpg",".jpeg",".png",".webp",".gif")

        files = sorted(
            f for f in os.listdir(image_dir)
            if f.lower().endswith(exts)
        )

        with open("images.json","w") as f:
            json.dump(files,f,indent=2)
        EOF

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        git add images.json

        git diff --cached --quiet || \
        git commit -m "Update image list"

        git push
